<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="VA1ADMIS5LKXPN2" ignored="1" name="test1" tests="3" failures="1" timestamp="01 May 2020 17:14:39 GMT" time="0.254" errors="0">
  <testcase name="testPrintMessage" time="0.064" classname="testngexamples.GroupTestExample"/>
  <testcase name="testSalutationMessage" time="0.02" classname="testngexamples.GroupTestExample"/>
  <testcase name="testSalutationMessage2" time="0.016" classname="testngexamples.GroupTestExample">
    <failure type="java.lang.AssertionError" message="expected [tutorialspointtutorialspoint.com] but found [tutorialspoint.com]">
      <![CDATA[java.lang.AssertionError: expected [tutorialspointtutorialspoint.com] but found [tutorialspoint.com]
	at testngexamples.GroupTestExample.testSalutationMessage2(GroupTestExample.java:25)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testSalutationMessage2 -->
  <testcase name="testingExitMessage" time="0.0" classname="testngexamples.GroupTestExample">
    <ignored/>
  </testcase> <!-- testingExitMessage -->
</testsuite> <!-- test1 -->
